apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-outbox-worker
  labels:
    app.kubernetes.io/name: app-outbox-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-outbox-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-outbox-worker
    spec:
      containers:
        - name: app-outbox-worker
          image: ghcr.io/daffahilmyf/go-impl-postgres-ha:latest
          imagePullPolicy: IfNotPresent
          args: ["outbox-worker", "--config", "/etc/app/config.yaml"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: app-config
              mountPath: /etc/app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: app-config
