apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-api.yaml
  - deployment-outbox-worker.yaml
  - deployment-consumer.yaml
  - service-api.yaml
  - sealed-secret.yaml

configMapGenerator:
  - name: app-config
    files:
      - config.yaml

generatorOptions:
  disableNameSuffixHash: true
